---
- name: Install virtualenvwrapper for Python 3.5
  pip:
    name: virtualenvwrapper

- name: Set virtualenvwrapper in global bashrc
  lineinfile:
    dest: /etc/bashrc
    line: "{{ item.line }}"
  with_items:
    - { line: '# virtualenvwrapper Setup' }
    - { line: 'export VIRTUALENV_PYTHON=/usr/bin/python3.5' }
    - { line: 'source /usr/bin/virtualenvwrapper.sh' }
