---
- name: Create vagrant PostgreSQL database user
  postgresql_user: name=vagrant role_attr_flags=SUPERUSER state=present
  become: yes
  become_user: postgres
  become_method: sudo

- name: Create vagrant PostgreSQL database
  postgresql_db: name=vagrant owner=vagrant state=present
  become: yes
  become_user: postgres
  become_method: sudo
