---
- name: Install development tools with yum
  yum:
    name: "@Development tools"
    state: present
- name: Remove CentOS git; we'll install git 2.x below
  yum: 
    name: 
      - git
    state: absent
- name: Install git, vim, vind-utils, and dependencies for pip installs with yum
  yum: 
    name: 
      - git2u
      - vim
      - bind-utils
      - zlib-devel
      - sqlite-devel
      - bzip2-devel
      - graphviz-devel
      - openssl-devel
      - libffi-devel
      - libjpeg-turbo-devel
      - giflib
      - tmux
      - libmemcached-devel
    state: present
