---
- name: Install Node.js RPM repository
  yum_repository:
    name: nodejs
    description: NodeJS 8
    baseurl: https://rpm.nodesource.com/pub_8.x/el/7/x86_64/

- name: Install Node.js and development tools
  yum:
    name: '{{ item }}'
  with_items:
    - nodejs
    - gcc-c++
    - make
