---
- name: Install FreeTDS
  yum:
    name: 
      - unixODBC-devel
      - freetds-devel
    state: present

- name: Add FreeTDS to /etc/odbcinst.ini as a driver
  lineinfile:
    dest: /etc/odbcinst.ini
    line: "{{ item.line }}"
  with_items:
    - { line: '[FreeTDS]' }
    - { line: 'Description = v0.95 with protocol v7.3' }
    - { line: 'Driver = /usr/lib64/libtdsodbc.so' }
