---
- name: Install FreeTDS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - unixODBC-devel
   - freetds-devel

- name: Copy odbcinst.ini to /etc
  copy:
    src: ../files/odbcinst.ini
    dest: /etc/odbcinst.ini
