---
- name: Install MS's ODBC Driver Repo
  get_url:
    url: https://packages.microsoft.com/config/rhel/7/prod.repo
    dest: /etc/yum.repos.d/mssql-release.repo

- name: Ensure utf16 packages are not installed to avoid conflicts
  yum:
    name: 
      - unixODBC-utf16
      - unixODBC-utf16-devel
    state: absent

- name: Install Microsoft ODBC Driver 17 for SQL Server for Linux
  yum:
    name: 
      - msodbcsql17
      - mssql-tools
      - unixODBC-devel
    state: present
  environment:
    ACCEPT_EULA: "Y"

- name: Install unixODBC
  yum:
    name: unixODBC-devel
    state: present
