---
- name: Configure vagrant box
  hosts: all
  become: yes
  roles:
    - { role: vagrant_configure, tags: ['setup'] }
    - { role: remote_repo_configure, tags: ['remote_repo'] }
    - { role: yum_update, tags: ['yum_update'] }
