---
- name: Install firewalld from RHEL
  yum:
    name: 'firewalld'
    state: present

- name: Make sure httpd is started at boot.
  service:
    name: firewalld
    enabled: true
    state: started

# Django's Runserver
- firewalld:
    port: 8000/tcp
    permanent: true
    state: enabled